GET http://localhost:8800/api/v1/categori

###
POST http://localhost:8800/api/v1/categori
Content-Type: application/json

{
    "nama": "Rumah fgse",
    "keterangan": "sfef"
}

###
PUT http://localhost:8800/api/v1/categori/a9bafb6b-96ca-41d1-8408-686a79500bd6
Content-Type: application/json

{
    "nama": "Perhiasan",
    "keterangan": "Emas dan perak"
}

###
GET http://localhost:8800/api/v1/categori/a9bafb6b-96ca-41d1-8408-686a79500bd6

###
DELETE http://localhost:8800/api/v1/categori/dadwd

###
POST http://localhost:8800/api/v1/auth/register
Content-Type: application/json

{
    "nama": "Nanang Setiawan",
    "email": "nanang@mail.com",
    "password": "12345678"

}

###
GET http://localhost:8800/api/v1/user

###
GET http://localhost:8800/api/v1/user/882266e1-fb86-4e28-9a68-ac0d6a3d6283

###
DELETE  http://localhost:8800/api/v1/user/1234567

###
PUT http://localhost:8800/api/v1/user/882266e1-fb86-4e28-9a68-ac0d6a3d6283
Content-Type: application/json

{
    "nama": "Nanang Hirate",
    "email": "yurina@mail.com",
    "password": "12345678",
    "avatar" :"https://cdn.idntimes.com/content-images/community/2022/07/800-800-102400-6-6a67b520ee3ebcc423c99333ede97ee3-707e8c6c19374607064f32578e27a733_600x400.jpg"
}

###
POST http://localhost:8800/api/v1/satuan
Content-Type: application/json

{
    "nama": "Box",
    "keterangan": "Satu item"
}

###
GET http://localhost:8800/api/v1/satuan

###
GET http://localhost:8800/api/v1/satuan/daw

###
PUT http://localhost:8800/api/v1/satuan/daw
Content-Type: application/json

{
    "nama": "Boxx",
    "keterangan": "50 item"
}

###
DELETE http://localhost:8800/api/v1/satuan/daw

###
POST http://localhost:8800/api/v1/barang
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWRfdXNlciI6IjM3MjJhYzc5LTIyYzktNDNmMy1hOTYxLTg2NzZjMTY5NDU1MCIsIm5hbWEiOiJOYW5hbmcgU2V0aWF3YW4iLCJlbWFpbCI6Im5hbmFuZ0BtYWlsLmNvbSIsImlzU3VwZXJBZG1pbiI6MCwiaWF0IjoxNjcwNTc0OTEzLCJleHAiOjE2NzA1NzQ5MzN9.loiEARHr4gBo3LS6tT55So4KOe-XHOFPAvJVSjkjumc
Content-Type: application/json

{
    "nama": "Kopi Lawak",
    "harga": 7000,
    "qty" :102,
    "_id_satuan" : "36e623ad-952e-4e15-a204-d89db7d9aff4",
    "_id_kategori" : "67d9a679-e268-4d06-ab07-ede521f2f5c4"
}

###
GET http://localhost:8800/api/v1/barang/19dec8e1-05e2-4dc1-a001-520aa377988b


###
GET http://localhost:8800/api/v1/barang/

###
GET http://localhost:8800/api/v1/barang/barang/983e0c15-c606-46ea-a9a7-644d51b0b3d6

###
PUT  http://localhost:8800/api/v1/barang/d6f1eb03-b890-429a-8dbd-17593b6333db
Content-Type: application/json

{
    "nama": "Kopi Liar",
    "harga": 17000,
    "qty" :50,
    "_id_satuan" : "36e623ad-952e-4e15-a204-d89db7d9aff4",
    "_id_kategori" : "67d9a679-e268-4d06-ab07-ede521f2f5c4"
}

###
DELETE  http://localhost:8800/api/v1/barang/dadwadwa

TRANSAKSI

###
GET  http://localhost:8800/api/v1/transaksi/

###
POST  http://localhost:8800/api/v1/transaksi
Content-Type: application/json

{
    "_id_admin": "daw",
    "invoice": 20210520002,
    "sub_total": 100000,
    "diskon": 20,
    "total": 80000,
    "detail_transaksi": [
        {
        "_id_master_transaksi" : 1,
        "_id_barang" : "ad68b5c5-5818-45e3-b06d-00e3d9746ef5",
        "harga": 20,
        "qty": 1,
        "sub_total" : 3434343
        },
                {
        "_id_master_transaksi" : 1,
        "_id_barang" : "ad68b5c5-5818-45e3-b06d-00e3d9746ef5",
        "harga": 100,
        "qty": 1,
        "sub_total" : 3434343
        }
    ]
}

###
DELETE  http://localhost:8800/api/v1/transaksi/0e326d28-b3bb-46c9-81c9-6a97b2706d45

###
GET http://localhost:8800/api/v1/transaksi/detail-transaksi/44

###
DELETE http://localhost:8800/api/v1/transaksi/detail-transaksi/detail/22

###
DELETE http://localhost:8800/api/v1/transaksi/detail-transaksi/55

Login
###
POST http://localhost:8800/api/v1/auth/login
Content-Type: application/json

{
    "email": "nanang@mail.com",
    "password": "12345678"
}

###
GET http://localhost:8800/api/v1/barang/19dec8e1-05e2-4dc1-a001-520aa377988b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWRfdXNlciI6IjM3MjJhYzc5LTIyYzktNDNmMy1hOTYxLTg2NzZjMTY5NDU1MCIsIm5hbWEiOiJOYW5hbmcgU2V0aWF3YW4iLCJlbWFpbCI6Im5hbmFuZ0BtYWlsLmNvbSIsImlzU3VwZXJBZG1pbiI6MCwiaWF0IjoxNjcwNTc4NDI0LCJleHAiOjE2NzA1Nzg0NDR9.9eIIJISThoPsv_1QyHs9Qr0znATiKBn5m9t73GGrWqw

###
GET http://localhost:8800/api/v1/auth/token